#!/bin/sh

ROOT_DIR=`erl -eval 'io:format("~s~n", [code:lib_dir("log_roller")])' -s init stop -noshell`
HOSTNAME=`case \`uname\` in Darwin ) echo \`hostname\`;; * ) echo \`hostname --fqdn\`;; esac`
SASL='-sasl sasl_error_logger false -sasl errlog_type all -sasl error_logger_mf_dir "/var/log/log_roller" -sasl error_logger_mf_maxbytes 10485760 -sasl error_logger_mf_maxfiles 1'

case $1 in
'dev' )
	erl -pa ebin -name log_roller@$HOSTNAME +W w +A 1 -config priv/log_roller -boot log_roller -log_roller_type subscriber -webtool start
	;;
'console' )
	erl -name log_roller@$HOSTNAME +W w +A 1 -config $ROOT_DIR/priv/log_roller -boot log_roller -log_roller_type subscriber -webtool start $SASL
	;;
'start' )
    erl -detached -name log_roller@$HOSTNAME +W w +A 1 -config $ROOT_DIR/priv/log_roller -boot log_roller -log_roller_type subscriber -webtool start -noshell $SASL
    ;;
'stop' )
    erl -name logrollerctl@$HOSTNAME -pa $ROOT_DIR/ebin -noshell -s log_roller stop -s init stop -- log_roller@$HOSTNAME
    ;;
*)
   echo "usage: `basename $0` {dev|start|stop}"
esac
